

create or replace procedure crearCONDUCTOR (newidCONDUCTOR number , NEWDPI NUMBER, NEWNUMEROLICENCIA NUMBER, NEWNOMBRE VARCHAR2, NEWAPELLIDO VARCHAR2, NEWTELEFONO NUMBER, NEWIDLICENCIA NUMBER)

is 

begin 
insert into CONDUCTOR values (newidCONDUCTOR, NEWDPI, NEWNUMEROLICENCIA, NEWNOMBRE, NEWAPELLIDO, NEWTELEFONO, NEWIDLICENCIA);
commit;
end crearCONDUCTOR;


create or replace procedure crearlicencia (newidlicencia number , newlicencia char)

is 

begin 
insert into licencia values (newidlicencia, newlicencia);
commit;
end crearlicencia;


create or replace procedure crearVEHICULO  (newidVEHICULO  number , NEWPLACA NUMBER, NEWMARCA VARCHAR2, NEWMODELO  NUMBER, NEWCOLOR VARCHAR2, NEWCAPACIDAD NUMBER, NEWIDCONDUCTOR NUMBER)

is 

begin 
insert into VEHICULO  values (newidVEHICULO  , NEWPLACA , NEWMARCA, NEWMODELO  , NEWCOLOR , NEWCAPACIDAD , NEWIDCONDUCTOR);
commit;
end crearVEHICULO;

create or replace PROCEDURE PRC_AUDITORIA(PNOMBRETABLA IN VARCHAR2, PLLAVE IN VARCHAR2, PNOMBRECAMPO IN VARCHAR2, PVALORANTERIOR IN VARCHAR2, PVALORNUEVO IN VARCHAR2, POBSERVACIONES IN VARCHAR2) IS
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
	BEGIN
		INSERT INTO AUDITORIA(FECHA, USUARIO, NOMBRETABLA, LLAVE, NOMBRECAMPO, VALORANTERIOR, VALORNUEVO, OBSERVACIONES)
		VALUES (SYSDATE, USER, PNOMBRETABLA, PLLAVE, PNOMBRECAMPO, PVALORANTERIOR, PVALORNUEVO, POBSERVACIONES);
		COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
				ROLLBACK;
		END;
END;


