CREATE TABLE LICENCIA(
IDLICENCIA NUMBER(5),
LICENCIA CHAR(2),
CONSTRAINT LICENCIA Primary key (IDLICENCIA)
);

CREATE TABLE CONDUCTOR (
IDCONDUCTOR NUMBER(10),
DPI NUMBER(15),
NUMEROLICENCIA VARCHAR2 (20),
NOMBRE VARCHAR2(50),
APELLIDO VARCHAR2(50),
TELEFONO NUMBER (15),
IDLICENCIA NUMBER (5),
CONSTRAINT CONDUCTOR  Primary key (IDCONDUCTOR)
);
alter table CONDUCTOR
   add constraint CON_LI foreign key (IDLICENCIA)
      references LICENCIA (IDLICENCIA);
      
CREATE TABLE VEHICULO (
IDVEHICULO NUMBER(10),
PLACA VARCHAR2(15),
MARCA VARCHAR2 (20),
MODELO VARCHAR2(50),
COLOR VARCHAR2(50),
CAPACIDADMAX NUMBER (15),
IDCONDUCTOR NUMBER(10),
CONSTRAINT VEHICULO  Primary key (IDVEHICULO)
);
alter table VEHICULO
   add constraint VEH_CON foreign key (IDCONDUCTOR)
      references CONDUCTOR (IDCONDUCTOR);        
      

CREATE TABLE ESTADO (
IDESTADO NUMBER(10),
NOMBRE_ESTADO VARCHAR2(50),
CONSTRAINT ESTADO  Primary key (IDESTADO)
);

CREATE TABLE TIPO_USUARIO (
IDTIPOUSUARIO NUMBER(10),
DESCRIPCION VARCHAR2(15),
CONSTRAINT TIPO_USUARIO  Primary key (IDTIPOUSUARIO)
);


CREATE TABLE USUARIO (
IDUSUARIO NUMBER(10),
NOMBRE VARCHAR2(15),
APELLIDO VARCHAR2 (20),
NOMBREUSUARIO VARCHAR2(50),
PASWORD VARCHAR2(50),
IDTIPOUSUARIO NUMBER(10),
CONSTRAINT USUARIO  Primary key (IDUSUARIO)
);
alter table USUARIO
   add constraint USU_TIP foreign key (IDTIPOUSUARIO)
      references TIPO_USUARIO (IDTIPOUSUARIO); 

CREATE TABLE DEPARTAMENTO (
IDDEPARTAMENTO NUMBER (3),
NOMBREDEPARTAMENTO VARCHAR2(50),
CONSTRAINT DEPARTAMENTO Primary key (IDDEPARTAMENTO)
);


CREATE TABLE SUCURSAL  (
IDSUCURSAL  NUMBER (3),
NOMBRESUCURSAL VARCHAR2(50),
IDDEPARTAMENTO NUMBER (3),
CONSTRAINT SUCURSAL Primary key (IDSUCURSAL)
);
alter table SUCURSAL
   add constraint SUC_DEP foreign key (IDDEPARTAMENTO)
      references DEPARTAMENTO (IDDEPARTAMENTO);
      
 CREATE TABLE CLIENTE  (
IDCLIENTE  NUMBER (3),
NOMBRE VARCHAR2(50),
APELLIDO VARCHAR2(50),
DPI NUMBER (20),
CONSTRAINT CLIENTE Primary key (IDCLIENTE)
);     
      
CREATE TABLE DETALLE_VENTA  (
IDVENTA  NUMBER (3),
MERCADERIA VARCHAR2(50),
COSTO_UNITARIO NUMBER (18,2),
CANTIDAD NUMBER (3),
IDCLIENTE NUMBER(3),
TOTAL NUMBER (18,2),
FECHA_ENTREGA DATE,
DEPARTAMENTO_ENTREGA VARCHAR2(50),
CONSTRAINT DETALLE_VENTA Primary key (IDVENTA)
);
alter table DETALLE_VENTA
   add constraint CAR_CLI foreign key (IDCLIENTE)
      references CLIENTE (IDCLIENTE);     
      
      
 alter table DETALLE_VENTA
  drop column DEPARTAMENTO_ENTREGA;
        
DROP TABLE DETALLE_VENTA cascade constraints;

CREATE TABLE DETALLE_VENTA  (
IDVENTA  NUMBER (3),
IDDEPARTAMENTO  NUMBER (3),
IDCLIENTE NUMBER(3),
MERCADERIA VARCHAR2(50),
COSTO_UNITARIO NUMBER (18,2),
CANTIDAD NUMBER (3),
TOTAL NUMBER (18,2),
FECHA_ENTREGA DATE,
CONSTRAINT DETALLE_VENTA Primary key (IDVENTA),
CONSTRAINT DETVENT_DEPTO FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO),
CONSTRAINT DETVENT_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);
    
 CREATE TABLE CARGO (
ID_CARGO NUMBER (10),
IDUSUARIO NUMBER(10),
IDVEHICULO NUMBER(10),
FECHA_ENVIDO DATE,
IDSUCURSAL  NUMBER (3),
IDVENTA NUMBER(3),
total number (10,2),
CONSTRAINT CARGO Primary key (ID_CARGO)
); 
alter table CARGO
   add constraint CAR_CL foreign key (IDVENTA)
      references DETALLE_VENTA (IDVENTA);
      
alter table CARGO
   add constraint CAR_USU foreign key (IDUSUARIO)
      references USUARIO (IDUSUARIO);
alter table CARGO
   add constraint CAR_VEH foreign key (IDVEHICULO)
      references VEHICULO (IDVEHICULO);
alter table CARGO
   add constraint CAR_SUC foreign key (IDSUCURSAL)
      references SUCURSAL (IDSUCURSAL);

CREATE TABLE CARGO_ESTADO(
ID_CARGO NUMBER (10),
IDESTADO NUMBER(10),
CONSTRAINT CARGO_ESTADO Primary key (ID_CARGO)
);
alter table CARGO_ESTADO
   add constraint CE_CARG foreign key (ID_CARGO)
      references CARGO (ID_CARGO);  
      
alter table CARGO_ESTADO
   add constraint CE_ESTA foreign key (IDESTADO)
      references ESTADO (IDESTADO); 

CREATE TABLE TRACKIN_ENVIOS (
CARGO NUMBER(10),
IDESTADO NUMBER(10),
FECHA DATE );
alter table TRACKIN_ENVIOS
   add constraint TRACK_ESTADO foreign key (IDESTADO)
      references ESTADO (IDESTADO);
      

CREATE OR REPLACE TRIGGER TRACK 
AFTER INSERT ON CARGO_ESTADO 
FOR EACH ROW
BEGIN 
IF INSERTING THEN 
INSERT INTO TRACKIN_ENVIOS VALUES (:NEW.ID_CARGO,:new.IDESTADO,sysdate);
END IF;
END;


create or replace trigger Control_Precios
before insert on CARGO  for each row
begin
if :new.TOTAL >1000
then :new.TOTAL  := (:NEW.TOTAL-(:NEW.TOTAL*0.01 ));
end if;
end;

INSERT INTO LICENCIA VALUES ('1','A');
INSERT INTO LICENCIA VALUES ('2','B');
INSERT INTO LICENCIA VALUES ('3','C');
INSERT INTO LICENCIA VALUES ('4','M');

INSERT INTO CONDUCTOR VALUES ('1','2171814595','123456789','PEDRO','FERNANDEZ','78945678','1');

INSERT INTO VEHICULO VALUES ('1','12485','MAZDA','2018','ROJO','3','1');

INSERT INTO ESTADO VALUES ('1','RECEPCIONADO');
INSERT INTO ESTADO VALUES ('2','ENVIADO ');
INSERT INTO ESTADO VALUES ('3','ENTREGADO');

INSERT INTO TIPO_USUARIO VALUES ('1','ADMIN');

INSERT INTO USUARIO VALUES ('1','JUAN','PEREZ','JUANPE','1234','1');

INSERT INTO CLIENTE VALUES ('1','SANTOS','ZURDO','21789456');

INSERT INTO DEPARTAMENTO VALUES ('1','GUATEMLA');

INSERT INTO SUCURSAL VALUES ('1','SUCURSAL CENTRAL','1'); 

INSERT INTO DETALLE_VENTA VALUES ('1','PINTURA','5.20','100','1','789','12/8/2019','GUATEMALA');

INSERT INTO CARGO VALUES ('1','1','1','11/8/2019','1','1','500');

INSERT INTO CARGO_ESTADO VALUES ('1','1');


SELECT a.ID_CARGO , b.NOMBRE_ESTADO
FROM CARGO_ESTADO a, ESTADO b 
WHERE a.idestado = b.Idestado

















